import os
import uuid
import datetime
import torch
import numpy as np
import cv2
from PIL import Image
from torchvision import transforms as T
from utils.image_fetcher import fetch_satellite_image
from utils.geo_utils import get_meters_per_pixel, get_zoom_level_for_box

# Configuration
CONFIDENCE_THRESHOLD = 0.40
ARTIFACTS_DIR = os.path.join(os.path.dirname(__file__), "artifacts")

def get_transform():
    return T.Compose([T.ToTensor()])

def run_inference(model, lat: float, lon: float, buffer_sqft: int, device):
    """
    Main pipeline: Fetch -> Predict -> Quantify -> visualize
    Two-step buffer logic: Try 1200 sqft first, expand to 2400 if no detection
    """
    # Try initial buffer
    result = _run_inference_single_buffer(model, lat, lon, buffer_sqft, device)
    
    # If no solar found and we're at 1200 sqft, try 2400 sqft
    if not result["solar_present"] and buffer_sqft == 1200:
        print(f"No solar found in 1200 sqft buffer, expanding to 2400 sqft...")
        result = _run_inference_single_buffer(model, lat, lon, 2400, device)
    
    return result

def _run_inference_single_buffer(model, lat: float, lon: float, buffer_sqft: int, device):
    """
    Run inference for a single buffer size
    """
    # 1. Fetch Image
    zoom_level = get_zoom_level_for_box(lat, buffer_sqft)
    image_pil, is_mock = fetch_satellite_image(lat, lon, zoom=zoom_level)
    
    # 2. Preprocess
    img_tensor = get_transform()(image_pil).to(device)
    
    # 3. Predict
    print(f"Running prediction...")
    with torch.no_grad():
        prediction = model([img_tensor])[0]
    
    # 4. Filter Results
    scores = prediction['scores'].cpu().numpy()
    masks = prediction['masks'].cpu().numpy()
    boxes = prediction['boxes'].cpu().numpy()
    
    # Debug: Show max score
    if len(scores) > 0:
        print(f"Max confidence score: {np.max(scores):.4f}, Total predictions: {len(scores)}")
    else:
        print("No predictions generated by model")
    
    valid_indices = np.where(scores > CONFIDENCE_THRESHOLD)[0]
    
    print(f"Found {len(valid_indices)} detections above threshold {CONFIDENCE_THRESHOLD}")
    
    solar_present = len(valid_indices) > 0
    total_area_pixels = 0
    
    # Create valid mask overlay
    img_np = np.array(image_pil)
    overlay_img = img_np.copy()
    
    # Color for mask (Green with transparency)
    mask_color = np.array([0, 255, 0]) 
    
    for idx in valid_indices:
        mask = masks[idx, 0]
        # Binarize mask
        mask_binary = mask > 0.5
        total_area_pixels += np.sum(mask_binary)
        
        # Draw overlay
        # Simple color blending
        overlay_img[mask_binary] = (overlay_img[mask_binary] * 0.5 + mask_color * 0.5).astype(np.uint8)
        
        # Draw bounding box
        box = boxes[idx].astype(int)
        cv2.rectangle(overlay_img, (box[0], box[1]), (box[2], box[3]), (0, 255, 0), 2)

    # 5. Quantify Area
    meters_per_pixel = get_meters_per_pixel(lat, zoom_level)
    area_sq_meters = total_area_pixels * (meters_per_pixel ** 2)
    
    # 6. Save Artifacts
    if not os.path.exists(ARTIFACTS_DIR):
        os.makedirs(ARTIFACTS_DIR)
        
    sample_id = str(uuid.uuid4())
    
    # Save original
    original_path = os.path.join(ARTIFACTS_DIR, f"original_{sample_id}.png")
    image_pil.save(original_path)
    
    # Save overlay
    overlay_pil = Image.fromarray(overlay_img)
    overlay_path = os.path.join(ARTIFACTS_DIR, f"overlay_{sample_id}.png")
    overlay_pil.save(overlay_path)
    
    # 7. Construct Result
    return {
        "sample_id": sample_id,
        "latitude": lat,
        "longitude": lon,
        "solar_present": bool(solar_present),
        "solar_area_m2": float(round(area_sq_meters, 2)),
        "confidence": float(round(scores[valid_indices[0]], 2)) if len(valid_indices) > 0 else 0.0,
        "qc_status": "VERIFIABLE" if solar_present else "NOT_VERIFIABLE",
        "is_mock_data": is_mock,
        "buffer_size_sqft": buffer_sqft,
        "model_version": "v1.0",
        "timestamp": datetime.datetime.utcnow().isoformat(),
        "artifact_paths": {
            "original": f"/static/original_{sample_id}.png",
            "overlay": f"/static/overlay_{sample_id}.png"
        }
    }
